stages:
  - build
  - deploy

build:
  stage: build
  script:
    - NODE_VERSION=$(cat ./.nvmrc)
    - VERSION_LENGTH=${#NODE_VERSION}
    -
      (
      if [ $VERSION_LENGTH -gt 0 ];
      then
      echo "changing node version to $NODE_VERSION";
      nvm install;
      nvm use;
      node -v;
      whereis node;
      node -v;
      npm -v;
      fi;
      echo "build app";
      npm install
      npm run build
      cd website
      npm install
      npm run build
      )



