stages:
  - build

build:
  only:
    - schedules
  stage: build
  script:
    - NODE_VERSION=$(cat ./.nvmrc)
    - VERSION_LENGTH=${#NODE_VERSION}
    -
      (
      if [ $VERSION_LENGTH -gt 0 ];
      then
      echo "changing node version to $NODE_VERSION";
      nvm install;
      nvm use;
      node -v;
      whereis node;
      node -v;
      npm -v;
      fi;
      echo "build app";
      npm install;
      npm run build;
      cd website;
      npm install;
      npm run build;
      cd -;
      ls -l;
      echo "deploy";
      sh /usr/local/bin/wj-rsync.sh webjet2b.srv.iway.local website/build /www/tomcat_au20/webapps/elements_webjet_sk/ tomcat_au20 tomcat_au20;
      )

  artifacts:
    paths:
      - website/build
    expire_in: 2 days
