import globals from 'globals';
import { default as wc } from 'eslint-plugin-wc';
import { default as importPlugin } from 'eslint-plugin-import';
import jsdoc from 'eslint-plugin-jsdoc';

export default [
  jsdoc.configs['flat/contents-typescript-error'],
  jsdoc.configs['flat/logical-typescript-error'],
  jsdoc.configs['flat/stylistic-typescript-error'],
  {
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        myCustomGlobal: 'readonly',
      },
    },
    plugins: {
      wc: wc,
      import: importPlugin,
    },
    settings: {
      wc: {
        elementBaseClasses: ['WJElement'], // Recognize `LitElement` as a Custom Element base class
      },
    },
    ignores: [
      '.cache',
      'demo',
      'dist',
      'docs',
      'experimental-packages',
      'node_modules',
      '**/plugins/*.js',
      '**/plugins/**/*.js',
      '**/*.test.js',
    ],
    rules: {
      'array-callback-return': 'error',
      'comma-dangle': 'off',
      'consistent-return': 'error',
      curly: 'off',
      'default-param-last': 'error',
      eqeqeq: 'error',
      'func-names': ['warn', 'never'],
      'import/no-duplicates': 'warn',
      'jsdoc/check-tag-names': [
        'error',
        {
          definedTags: [
            'documentation',
            'status',
            'summary',
            'extends',
            'dependency',
            'slot',
            'csspart',
            'tag',
            'cssproperty',
            'fires',
            'attr',
          ],
          enableFixer: false,
        },
      ],
      'jsdoc/lines-before-block': 'off',
      'jsdoc/no-types': 'off',
      'jsdoc/require-hyphen-before-param-description': ['error', 'never'],
      'jsdoc/text-escaping': 'off',
      'jsdoc/valid-types': 'off',
      'no-array-constructor': 'error',
      'no-bitwise': 'error',
      'no-constructor-return': 'error',
      'no-else-return': 'off',
      'no-empty-function': 'warn',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-floating-decimal': 'error',
      'no-implicit-coercion': 'off',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-invalid-this': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-multi-assign': 'warn',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-object': 'error',
      'no-new-wrappers': 'error',
      'no-octal-escape': 'error',
      'no-proto': 'error',
      'no-restricted-imports': [
        'warn',
        {
          paths: [
            {
              name: '.',
              message: 'Usage of local index imports is not allowed.',
            },
            {
              name: './index',
              message: 'Import from the source file instead.',
            },
          ],
        },
      ],
      'no-return-assign': 'warn',
      'no-script-url': 'error',
      'no-self-compare': 'warn',
      'no-sequences': 'warn',
      'no-shadow': 'error',
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'warn',
      'no-useless-call': 'error',
      'no-useless-computed-key': 'warn',
      'no-useless-concat': 'error',
      'no-useless-rename': 'warn',
      'no-useless-return': 'warn',
      'no-var': 'error',
      'one-var': ['warn', 'never'],
      'operator-assignment': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-const': 'off',
      'prefer-numeric-literals': 'warn',
      'prefer-object-spread': 'warn',
      'prefer-promise-reject-errors': 'error',
      'prefer-rest-params': 'warn',
      'prefer-spread': 'warn',
      'prefer-template': 'off',
      radix: 'off',
      'require-await': 'error',
      'wc/attach-shadow-constructor': 'warn',
      'wc/define-tag-after-class-definition': 'off',
      'wc/expose-class-on-global': 'off',
      'wc/file-name-matches-element': 'off',
      'wc/guard-define-call': 'off',
      'wc/guard-super-call': 'error',
      'wc/max-elements-per-file': 'warn',
      'wc/no-child-traversal-in-attributechangedcallback': 'warn',
      'wc/no-child-traversal-in-connectedcallback': 'warn',
      'wc/no-closed-shadow-root': 'warn',
      'wc/no-constructor': 'off',
      'wc/no-constructor-attributes': 'error',
      'wc/no-constructor-params': 'warn',
      'wc/no-customized-built-in-elements': 'warn',
      'wc/no-exports-with-element': 'off',
      'wc/no-invalid-element-name': 'error',
      'wc/no-invalid-extends': 'warn',
      'wc/no-method-prefixed-with-on': 'warn',
      'wc/no-self-class': 'off',
      'wc/no-typos': 'warn',
      'wc/require-listener-teardown': 'warn',
      'wc/tag-name-matches-class': 'warn',
      'wrap-iife': ['warn', 'inside'],
    },
  },
];
