export const iconContent: Map<any, any>;
export function getSrc(src: string): string | null;
export function isSrc(str: string): boolean;
export function isSvgDataUrl(url: string): boolean;
export function isEncodedDataUrl(url: string): boolean;
export function isStr(val: any): boolean;
export function validateContent(svgContent: string): string;
export function isValid(elm: Element | Node): boolean;
export function getSvgContent(url: string, sanitize?: boolean): Promise<void>;
export function getUrl(i: HTMLElement): string | null;
export function getName(iconName: string): string | null;
