/**
 * This file is generated by `docs/scripts/generate-design-token-data.mjs`.
 * Do not edit manually.
 */

export const designTokenValues = {
  "--wje-font-family": {
    "light": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji'",
    "dark": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
    "lightResolved": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji'",
    "darkResolved": "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif"
  },
  "--wje-font-family-secondary": {
    "light": "'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
    "dark": "'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
    "lightResolved": "'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif",
    "darkResolved": "'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif"
  },
  "--wje-font-size-2x-small": {
    "light": "0.5rem",
    "dark": "0.5rem",
    "lightResolved": "0.5rem",
    "darkResolved": "0.5rem"
  },
  "--wje-font-size-x-small": {
    "light": "0.625rem",
    "dark": "0.625rem",
    "lightResolved": "0.625rem",
    "darkResolved": "0.625rem"
  },
  "--wje-font-size-small": {
    "light": "0.75rem",
    "dark": "0.75rem",
    "lightResolved": "0.75rem",
    "darkResolved": "0.75rem"
  },
  "--wje-font-size": {
    "light": "0.875rem",
    "dark": "0.875rem",
    "lightResolved": "0.875rem",
    "darkResolved": "0.875rem"
  },
  "--wje-font-size-medium": {
    "light": "1rem",
    "dark": "1rem",
    "lightResolved": "1rem",
    "darkResolved": "1rem"
  },
  "--wje-font-size-large": {
    "light": "1.25rem",
    "dark": "1.25rem",
    "lightResolved": "1.25rem",
    "darkResolved": "1.25rem"
  },
  "--wje-font-size-x-large": {
    "light": "1.5rem",
    "dark": "1.5rem",
    "lightResolved": "1.5rem",
    "darkResolved": "1.5rem"
  },
  "--wje-font-size-2x-large": {
    "light": "2.25rem",
    "dark": "2.25rem",
    "lightResolved": "2.25rem",
    "darkResolved": "2.25rem"
  },
  "--wje-font-size-3x-large": {
    "light": "3rem",
    "dark": "3rem",
    "lightResolved": "3rem",
    "darkResolved": "3rem"
  },
  "--wje-font-size-4x-large": {
    "light": "4.5rem",
    "dark": "4.5rem",
    "lightResolved": "4.5rem",
    "darkResolved": "4.5rem"
  },
  "--wje-font-weight-light": {
    "light": "300",
    "dark": "300",
    "lightResolved": "300",
    "darkResolved": "300"
  },
  "--wje-font-weight-normal": {
    "light": "400",
    "dark": "400",
    "lightResolved": "400",
    "darkResolved": "400"
  },
  "--wje-font-weight-medium": {
    "light": "500",
    "dark": "500",
    "lightResolved": "500",
    "darkResolved": "500"
  },
  "--wje-font-weight-semibold": {
    "light": "600",
    "dark": "600",
    "lightResolved": "600",
    "darkResolved": "600"
  },
  "--wje-font-weight-bold": {
    "light": "700",
    "dark": "700",
    "lightResolved": "700",
    "darkResolved": "700"
  },
  "--wje-line-height-denser": {
    "light": "1.2",
    "dark": "1.2",
    "lightResolved": "1.2",
    "darkResolved": "1.2"
  },
  "--wje-line-height-dense": {
    "light": "1.4",
    "dark": "1.4",
    "lightResolved": "1.4",
    "darkResolved": "1.4"
  },
  "--wje-line-height-normal": {
    "light": "1.5",
    "dark": "1.5",
    "lightResolved": "1.5",
    "darkResolved": "1.5"
  },
  "--wje-line-height-loose": {
    "light": "1.6",
    "dark": "1.6",
    "lightResolved": "1.6",
    "darkResolved": "1.6"
  },
  "--wje-line-height-looser": {
    "light": "1.8",
    "dark": "1.8",
    "lightResolved": "1.8",
    "darkResolved": "1.8"
  },
  "--wje-letter-spacing-tightest": {
    "light": "-0.05em",
    "dark": "-0.05em",
    "lightResolved": "-0.05em",
    "darkResolved": "-0.05em"
  },
  "--wje-letter-spacing-tighter": {
    "light": "-0.025em",
    "dark": "-0.025em",
    "lightResolved": "-0.025em",
    "darkResolved": "-0.025em"
  },
  "--wje-letter-spacing-normal": {
    "light": "0em",
    "dark": "0em",
    "lightResolved": "0em",
    "darkResolved": "0em"
  },
  "--wje-letter-spacing-wider": {
    "light": "0.025em",
    "dark": "0.025em",
    "lightResolved": "0.025em",
    "darkResolved": "0.025em"
  },
  "--wje-letter-spacing-widest": {
    "light": "0.05em",
    "dark": "0.05em",
    "lightResolved": "0.05em",
    "darkResolved": "0.05em"
  },
  "--wje-background": {
    "light": "var(--wje-color-contrast-0)",
    "dark": "var(--wje-color-contrast-2)",
    "lightResolved": "hsla(0, 0%, 100%, 1)",
    "darkResolved": "hsla(0, 0%, 0%, 1)"
  },
  "--wje-color": {
    "light": "hsl(0, 0%, 29%)",
    "dark": "var(--wje-color-contrast-11)",
    "lightResolved": "hsl(0, 0%, 29%)",
    "darkResolved": "hsla(0, 0%, 100%, 1)"
  },
  "--wje-border-color": {
    "light": "var(--wje-color-contrast-3)",
    "dark": "var(--wje-color-contrast-4)",
    "lightResolved": "hsla(240, 6%, 90%, 1)",
    "darkResolved": "hsla(240, 5%, 41%, 1)"
  },
  "--wje-color-menu": {
    "light": "hsl(220, 15%, 15%)",
    "dark": "hsl(220, 15%, 15%)",
    "lightResolved": "hsl(220, 15%, 15%)",
    "darkResolved": "hsl(220, 15%, 15%)"
  },
  "--wje-color-contrast": {
    "light": "hsl(0, 0%, 95%)",
    "dark": "hsl(210, 11%, 15%)",
    "lightResolved": "hsl(0, 0%, 95%)",
    "darkResolved": "hsl(210, 11%, 15%)"
  },
  "--wje-color-primary": {
    "light": "var(--wje-color-primary-11)",
    "dark": "var(--wje-color-primary-1)",
    "lightResolved": "hsla(254, 59%, 35%, 1)",
    "darkResolved": "hsla(254, 50%, 21%, 1)"
  },
  "--wje-color-complete": {
    "light": "var(--wje-color-complete-11)",
    "dark": "var(--wje-color-complete-1)",
    "lightResolved": "hsla(211, 100%, 28%, 1)",
    "darkResolved": "hsla(211, 91%, 16%, 1)"
  },
  "--wje-color-success": {
    "light": "var(--wje-color-success-11)",
    "dark": "var(--wje-color-success-1)",
    "lightResolved": "hsla(158, 93%, 23%, 1)",
    "darkResolved": "hsla(158, 93%, 13%, 1)"
  },
  "--wje-color-warning": {
    "light": "var(--wje-color-warning-11)",
    "dark": "var(--wje-color-warning-1)",
    "lightResolved": "hsla(47, 75%, 38%, 1)",
    "darkResolved": "hsla(47, 75%, 19%, 1)"
  },
  "--wje-color-danger": {
    "light": "var(--wje-color-danger-11)",
    "dark": "var(--wje-color-danger-1)",
    "lightResolved": "hsla(3, 81%, 31%, 1)",
    "darkResolved": "hsla(3, 82%, 17%, 1)"
  },
  "--wje-color-info": {
    "light": "var(--wje-color-info-11)",
    "dark": "var(--wje-color-info-1)",
    "lightResolved": "hsla(207, 36%, 16%, 1)",
    "darkResolved": "hsla(207, 36%, 16%, 1)"
  },
  "--wje-spacing-4x-small": {
    "light": "0.125rem",
    "dark": "0.125rem",
    "lightResolved": "0.125rem",
    "darkResolved": "0.125rem"
  },
  "--wje-spacing-3x-small": {
    "light": "0.25rem",
    "dark": "0.25rem",
    "lightResolved": "0.25rem",
    "darkResolved": "0.25rem"
  },
  "--wje-spacing-2x-small": {
    "light": "0.375rem",
    "dark": "0.375rem",
    "lightResolved": "0.375rem",
    "darkResolved": "0.375rem"
  },
  "--wje-spacing-x-small": {
    "light": "0.5rem",
    "dark": "0.5rem",
    "lightResolved": "0.5rem",
    "darkResolved": "0.5rem"
  },
  "--wje-spacing-small": {
    "light": "0.75rem",
    "dark": "0.75rem",
    "lightResolved": "0.75rem",
    "darkResolved": "0.75rem"
  },
  "--wje-spacing-medium": {
    "light": "1rem",
    "dark": "1rem",
    "lightResolved": "1rem",
    "darkResolved": "1rem"
  },
  "--wje-spacing-large": {
    "light": "1.5rem",
    "dark": "1.5rem",
    "lightResolved": "1.5rem",
    "darkResolved": "1.5rem"
  },
  "--wje-spacing-x-large": {
    "light": "2rem",
    "dark": "2rem",
    "lightResolved": "2rem",
    "darkResolved": "2rem"
  },
  "--wje-spacing-2x-large": {
    "light": "2.5rem",
    "dark": "2.5rem",
    "lightResolved": "2.5rem",
    "darkResolved": "2.5rem"
  },
  "--wje-spacing-3x-large": {
    "light": "3rem",
    "dark": "3rem",
    "lightResolved": "3rem",
    "darkResolved": "3rem"
  },
  "--wje-spacing-4x-large": {
    "light": "4.5rem",
    "dark": "4.5rem",
    "lightResolved": "4.5rem",
    "darkResolved": "4.5rem"
  },
  "--wje-border-style": {
    "light": "solid",
    "dark": "solid",
    "lightResolved": "solid",
    "darkResolved": "solid"
  },
  "--wje-border-width": {
    "light": "1px",
    "dark": "1px",
    "lightResolved": "1px",
    "darkResolved": "1px"
  },
  "--wje-border-radius-small": {
    "light": "0.125rem",
    "dark": "0.125rem",
    "lightResolved": "0.125rem",
    "darkResolved": "0.125rem"
  },
  "--wje-border-radius-medium": {
    "light": "0.25rem",
    "dark": "0.25rem",
    "lightResolved": "0.25rem",
    "darkResolved": "0.25rem"
  },
  "--wje-border-radius-large": {
    "light": "0.5rem",
    "dark": "0.5rem",
    "lightResolved": "0.5rem",
    "darkResolved": "0.5rem"
  },
  "--wje-border-radius-x-large": {
    "light": "0.75rem",
    "dark": "0.75rem",
    "lightResolved": "0.75rem",
    "darkResolved": "0.75rem"
  },
  "--wje-border-radius-2x-large": {
    "light": "1rem",
    "dark": "1rem",
    "lightResolved": "1rem",
    "darkResolved": "1rem"
  },
  "--wje-border-radius-circle": {
    "light": "50%",
    "dark": "50%",
    "lightResolved": "50%",
    "darkResolved": "50%"
  },
  "--wje-border-radius-pill": {
    "light": "50rem",
    "dark": "50rem",
    "lightResolved": "50rem",
    "darkResolved": "50rem"
  },
  "--wje-shadow-small": {
    "light": "0 1px 2px rgba(0, 0, 0, 0.05)",
    "dark": "0 1px 2px rgba(0, 0, 0, 0.05)",
    "lightResolved": "0 1px 2px rgba(0, 0, 0, 0.05)",
    "darkResolved": "0 1px 2px rgba(0, 0, 0, 0.05)"
  },
  "--wje-shadow-medium": {
    "light": "2px 2px 11px 0px hsla(0, 0%, 0%, 0.08)",
    "dark": "2px 2px 11px 0px hsla(0, 0%, 0%, 0.08)",
    "lightResolved": "2px 2px 11px 0px hsla(0, 0%, 0%, 0.08)",
    "darkResolved": "2px 2px 11px 0px hsla(0, 0%, 0%, 0.08)"
  },
  "--wje-shadow-large": {
    "light": "0 4px 8px rgba(0, 0, 0, 0.1)",
    "dark": "0 4px 8px rgba(0, 0, 0, 0.1)",
    "lightResolved": "0 4px 8px rgba(0, 0, 0, 0.1)",
    "darkResolved": "0 4px 8px rgba(0, 0, 0, 0.1)"
  },
  "--wje-shadow-x-large": {
    "light": "0 8px 16px rgba(0, 0, 0, 0.1)",
    "dark": "0 8px 16px rgba(0, 0, 0, 0.1)",
    "lightResolved": "0 8px 16px rgba(0, 0, 0, 0.1)",
    "darkResolved": "0 8px 16px rgba(0, 0, 0, 0.1)"
  },
  "--wje-shadow-2x-large": {
    "light": "0 16px 32px rgba(0, 0, 0, 0.1)",
    "dark": "0 16px 32px rgba(0, 0, 0, 0.1)",
    "lightResolved": "0 16px 32px rgba(0, 0, 0, 0.1)",
    "darkResolved": "0 16px 32px rgba(0, 0, 0, 0.1)"
  },
  "--wje-transition-fast": {
    "light": "0.2s ease-in-out",
    "dark": "0.2s ease-in-out",
    "lightResolved": "0.2s ease-in-out",
    "darkResolved": "0.2s ease-in-out"
  },
  "--wje-transition-medium": {
    "light": "0.4s ease-in-out",
    "dark": "0.4s ease-in-out",
    "lightResolved": "0.4s ease-in-out",
    "darkResolved": "0.4s ease-in-out"
  },
  "--wje-transition-slow": {
    "light": "0.6s ease-in-out",
    "dark": "0.6s ease-in-out",
    "lightResolved": "0.6s ease-in-out",
    "darkResolved": "0.6s ease-in-out"
  }
} as const;

export const colorScaleValues = {
  "--wje-color-primary": {
    "light": [
      {
        "token": "--wje-color-primary-1",
        "value": "hsla(261, 70%, 96%, 1)"
      },
      {
        "token": "--wje-color-primary-2",
        "value": "hsla(260, 66%, 92%, 1)"
      },
      {
        "token": "--wje-color-primary-3",
        "value": "hsla(260, 64%, 88%, 1)"
      },
      {
        "token": "--wje-color-primary-4",
        "value": "hsla(260, 61%, 84%, 1)"
      },
      {
        "token": "--wje-color-primary-5",
        "value": "hsla(260, 63%, 80%, 1)"
      },
      {
        "token": "--wje-color-primary-6",
        "value": "hsla(259, 61%, 76%, 1)"
      },
      {
        "token": "--wje-color-primary-7",
        "value": "hsla(258, 61%, 72%, 1)"
      },
      {
        "token": "--wje-color-primary-8",
        "value": "hsla(257, 61%, 68%, 1)"
      },
      {
        "token": "--wje-color-primary-9",
        "value": "hsla(254, 67%, 62%, 1)"
      },
      {
        "token": "--wje-color-primary-10",
        "value": "hsla(254, 59%, 45%, 1)"
      },
      {
        "token": "--wje-color-primary-11",
        "value": "hsla(254, 59%, 35%, 1)"
      }
    ],
    "dark": [
      {
        "token": "--wje-color-primary-1",
        "value": "hsla(254, 50%, 21%, 1)"
      },
      {
        "token": "--wje-color-primary-2",
        "value": "hsla(254, 52%, 24%, 1)"
      },
      {
        "token": "--wje-color-primary-3",
        "value": "hsla(254, 52%, 35%, 1)"
      },
      {
        "token": "--wje-color-primary-4",
        "value": "hsla(254, 54%, 39%, 1)"
      },
      {
        "token": "--wje-color-primary-5",
        "value": "hsla(254, 54%, 47%, 1)"
      },
      {
        "token": "--wje-color-primary-6",
        "value": "hsla(254, 54%, 53%, 1)"
      },
      {
        "token": "--wje-color-primary-7",
        "value": "hsla(254, 54%, 57%, 1)"
      },
      {
        "token": "--wje-color-primary-8",
        "value": "hsla(254, 68%, 66%, 1)"
      },
      {
        "token": "--wje-color-primary-9",
        "value": "hsla(254, 88%, 78%, 1)"
      },
      {
        "token": "--wje-color-primary-10",
        "value": "hsla(254, 70%, 81%, 1)"
      },
      {
        "token": "--wje-color-primary-11",
        "value": "hsla(254, 69%, 88%, 1)"
      }
    ]
  },
  "--wje-color-complete": {
    "light": [
      {
        "token": "--wje-color-complete-1",
        "value": "hsla(233, 90%, 96%, 1)"
      },
      {
        "token": "--wje-color-complete-2",
        "value": "hsla(229, 89%, 93%, 1)"
      },
      {
        "token": "--wje-color-complete-3",
        "value": "hsla(229, 86%, 89%, 1)"
      },
      {
        "token": "--wje-color-complete-4",
        "value": "hsla(229, 86%, 86%, 1)"
      },
      {
        "token": "--wje-color-complete-5",
        "value": "hsla(228, 85%, 82%, 1)"
      },
      {
        "token": "--wje-color-complete-6",
        "value": "hsla(226, 82%, 78%, 1)"
      },
      {
        "token": "--wje-color-complete-7",
        "value": "hsla(225, 83%, 74%, 1)"
      },
      {
        "token": "--wje-color-complete-8",
        "value": "hsla(223, 83%, 70%, 1)"
      },
      {
        "token": "--wje-color-complete-9",
        "value": "hsla(211, 100%, 60%, 1)"
      },
      {
        "token": "--wje-color-complete-10",
        "value": "hsla(211, 100%, 45%, 1)"
      },
      {
        "token": "--wje-color-complete-11",
        "value": "hsla(211, 100%, 28%, 1)"
      }
    ],
    "dark": [
      {
        "token": "--wje-color-complete-1",
        "value": "hsla(211, 91%, 16%, 1)"
      },
      {
        "token": "--wje-color-complete-2",
        "value": "hsla(211, 91%, 23%, 1)"
      },
      {
        "token": "--wje-color-complete-3",
        "value": "hsla(211, 91%, 31%, 1)"
      },
      {
        "token": "--wje-color-complete-4",
        "value": "hsla(211, 93%, 35%, 1)"
      },
      {
        "token": "--wje-color-complete-5",
        "value": "hsla(211, 93%, 39%, 1)"
      },
      {
        "token": "--wje-color-complete-6",
        "value": "hsla(211, 93%, 44%, 1)"
      },
      {
        "token": "--wje-color-complete-7",
        "value": "hsla(211, 93%, 49%, 1)"
      },
      {
        "token": "--wje-color-complete-8",
        "value": "hsla(211, 93%, 55%, 1)"
      },
      {
        "token": "--wje-color-complete-9",
        "value": "hsla(211, 100%, 75%, 1)"
      },
      {
        "token": "--wje-color-complete-10",
        "value": "hsla(211, 100%, 81%, 1)"
      },
      {
        "token": "--wje-color-complete-11",
        "value": "hsla(211, 93%, 85%, 1)"
      }
    ]
  },
  "--wje-color-success": {
    "light": [
      {
        "token": "--wje-color-success-1",
        "value": "hsla(147, 44%, 95%, 1)"
      },
      {
        "token": "--wje-color-success-2",
        "value": "hsla(149, 41%, 90%, 1)"
      },
      {
        "token": "--wje-color-success-3",
        "value": "hsla(149, 40%, 85%, 1)"
      },
      {
        "token": "--wje-color-success-4",
        "value": "hsla(150, 41%, 80%, 1)"
      },
      {
        "token": "--wje-color-success-5",
        "value": "hsla(149, 42%, 75%, 1)"
      },
      {
        "token": "--wje-color-success-6",
        "value": "hsla(150, 41%, 70%, 1)"
      },
      {
        "token": "--wje-color-success-7",
        "value": "hsla(151, 42%, 65%, 1)"
      },
      {
        "token": "--wje-color-success-8",
        "value": "hsla(152, 42%, 59%, 1)"
      },
      {
        "token": "--wje-color-success-9",
        "value": "hsla(158, 67%, 45%, 1)"
      },
      {
        "token": "--wje-color-success-10",
        "value": "hsla(158, 74%, 30%, 1)"
      },
      {
        "token": "--wje-color-success-11",
        "value": "hsla(158, 93%, 23%, 1)"
      }
    ],
    "dark": [
      {
        "token": "--wje-color-success-1",
        "value": "hsla(158, 93%, 13%, 1)"
      },
      {
        "token": "--wje-color-success-2",
        "value": "hsla(158, 94%, 16%, 1)"
      },
      {
        "token": "--wje-color-success-3",
        "value": "hsla(158, 95%, 19%, 1)"
      },
      {
        "token": "--wje-color-success-4",
        "value": "hsla(158, 96%, 22%, 1)"
      },
      {
        "token": "--wje-color-success-5",
        "value": "hsla(158, 96%, 24%, 1)"
      },
      {
        "token": "--wje-color-success-6",
        "value": "hsla(158, 95%, 27%, 1)"
      },
      {
        "token": "--wje-color-success-7",
        "value": "hsla(158, 96%, 31%, 1)"
      },
      {
        "token": "--wje-color-success-8",
        "value": "hsla(158, 96%, 35%, 1)"
      },
      {
        "token": "--wje-color-success-9",
        "value": "hsla(158, 86%, 48%, 1)"
      },
      {
        "token": "--wje-color-success-10",
        "value": "hsla(158, 78%, 62%, 1)"
      },
      {
        "token": "--wje-color-success-11",
        "value": "hsla(158, 80%, 75%, 1)"
      }
    ]
  },
  "--wje-color-warning": {
    "light": [
      {
        "token": "--wje-color-warning-1",
        "value": "hsla(45, 100%, 96%, 1)"
      },
      {
        "token": "--wje-color-warning-2",
        "value": "hsla(47, 100%, 93%, 1)"
      },
      {
        "token": "--wje-color-warning-3",
        "value": "hsla(46, 100%, 90%, 1)"
      },
      {
        "token": "--wje-color-warning-4",
        "value": "hsla(46, 100%, 87%, 1)"
      },
      {
        "token": "--wje-color-warning-5",
        "value": "hsla(46, 100%, 84%, 1)"
      },
      {
        "token": "--wje-color-warning-6",
        "value": "hsla(46, 100%, 81%, 1)"
      },
      {
        "token": "--wje-color-warning-7",
        "value": "hsla(46, 100%, 77%, 1)"
      },
      {
        "token": "--wje-color-warning-8",
        "value": "hsla(47, 100%, 74%, 1)"
      },
      {
        "token": "--wje-color-warning-9",
        "value": "hsla(47, 100%, 67%, 1)"
      },
      {
        "token": "--wje-color-warning-10",
        "value": "hsla(47, 100%, 53%, 1)"
      },
      {
        "token": "--wje-color-warning-11",
        "value": "hsla(47, 75%, 38%, 1)"
      }
    ],
    "dark": [
      {
        "token": "--wje-color-warning-1",
        "value": "hsla(47, 75%, 19%, 1)"
      },
      {
        "token": "--wje-color-warning-2",
        "value": "hsla(47, 75%, 23%, 1)"
      },
      {
        "token": "--wje-color-warning-3",
        "value": "hsla(47, 75%, 27%, 1)"
      },
      {
        "token": "--wje-color-warning-4",
        "value": "hsla(47, 74%, 31%, 1)"
      },
      {
        "token": "--wje-color-warning-5",
        "value": "hsla(47, 78%, 37%, 1)"
      },
      {
        "token": "--wje-color-warning-6",
        "value": "hsla(47, 78%, 41%, 1)"
      },
      {
        "token": "--wje-color-warning-7",
        "value": "hsla(47, 78%, 45%, 1)"
      },
      {
        "token": "--wje-color-warning-8",
        "value": "hsla(47, 80%, 52%, 1)"
      },
      {
        "token": "--wje-color-warning-9",
        "value": "hsla(47, 80%, 67%, 1)"
      },
      {
        "token": "--wje-color-warning-10",
        "value": "hsla(47, 90%, 74%, 1)"
      },
      {
        "token": "--wje-color-warning-11",
        "value": "hsla(47, 90%, 80%, 1)"
      }
    ]
  },
  "--wje-color-danger": {
    "light": [
      {
        "token": "--wje-color-danger-1",
        "value": "hsla(9, 100%, 96%, 1)"
      },
      {
        "token": "--wje-color-danger-2",
        "value": "hsla(12, 100%, 91%, 1)"
      },
      {
        "token": "--wje-color-danger-3",
        "value": "hsla(11, 94%, 87%, 1)"
      },
      {
        "token": "--wje-color-danger-4",
        "value": "hsla(10, 91%, 83%, 1)"
      },
      {
        "token": "--wje-color-danger-5",
        "value": "hsla(9, 87%, 79%, 1)"
      },
      {
        "token": "--wje-color-danger-6",
        "value": "hsla(10, 82%, 74%, 1)"
      },
      {
        "token": "--wje-color-danger-7",
        "value": "hsla(8, 80%, 70%, 1)"
      },
      {
        "token": "--wje-color-danger-8",
        "value": "hsla(8, 77%, 65%, 1)"
      },
      {
        "token": "--wje-color-danger-9",
        "value": "hsla(3, 78%, 59%, 1)"
      },
      {
        "token": "--wje-color-danger-10",
        "value": "hsla(3, 68%, 41%, 1)"
      },
      {
        "token": "--wje-color-danger-11",
        "value": "hsla(3, 81%, 31%, 1)"
      }
    ],
    "dark": [
      {
        "token": "--wje-color-danger-1",
        "value": "hsla(3, 82%, 17%, 1)"
      },
      {
        "token": "--wje-color-danger-2",
        "value": "hsla(3, 82%, 19%, 1)"
      },
      {
        "token": "--wje-color-danger-3",
        "value": "hsla(3, 83%, 28%, 1)"
      },
      {
        "token": "--wje-color-danger-4",
        "value": "hsla(3, 83%, 32%, 1)"
      },
      {
        "token": "--wje-color-danger-5",
        "value": "hsla(3, 83%, 36%, 1)"
      },
      {
        "token": "--wje-color-danger-6",
        "value": "hsla(3, 83%, 40%, 1)"
      },
      {
        "token": "--wje-color-danger-7",
        "value": "hsla(3, 82%, 44%, 1)"
      },
      {
        "token": "--wje-color-danger-8",
        "value": "hsla(3, 72%, 58%, 1)"
      },
      {
        "token": "--wje-color-danger-9",
        "value": "hsla(3, 80%, 70%, 1)"
      },
      {
        "token": "--wje-color-danger-10",
        "value": "hsla(3, 80%, 76%, 1)"
      },
      {
        "token": "--wje-color-danger-11",
        "value": "hsla(4, 80%, 82%, 1)"
      }
    ]
  },
  "--wje-color-info": {
    "light": [
      {
        "token": "--wje-color-info-1",
        "value": "hsla(210, 5%, 92%, 1)"
      },
      {
        "token": "--wje-color-info-2",
        "value": "hsla(204, 6%, 85%, 1)"
      },
      {
        "token": "--wje-color-info-3",
        "value": "hsla(210, 7%, 78%, 1)"
      },
      {
        "token": "--wje-color-info-4",
        "value": "hsla(203, 5%, 71%, 1)"
      },
      {
        "token": "--wje-color-info-5",
        "value": "hsla(213, 6%, 65%, 1)"
      },
      {
        "token": "--wje-color-info-6",
        "value": "hsla(203, 6%, 58%, 1)"
      },
      {
        "token": "--wje-color-info-7",
        "value": "hsla(208, 6%, 52%, 1)"
      },
      {
        "token": "--wje-color-info-8",
        "value": "hsla(210, 7%, 45%, 1)"
      },
      {
        "token": "--wje-color-info-9",
        "value": "hsla(207, 20%, 35%, 1)"
      },
      {
        "token": "--wje-color-info-10",
        "value": "hsla(207, 16%, 27%, 1)"
      },
      {
        "token": "--wje-color-info-11",
        "value": "hsla(207, 36%, 16%, 1)"
      }
    ],
    "dark": [
      {
        "token": "--wje-color-info-1",
        "value": "hsla(207, 36%, 16%, 1)"
      },
      {
        "token": "--wje-color-info-2",
        "value": "hsla(207, 16%, 27%, 1)"
      },
      {
        "token": "--wje-color-info-3",
        "value": "hsla(207, 20%, 35%, 1)"
      },
      {
        "token": "--wje-color-info-4",
        "value": "hsla(210, 7%, 45%, 1)"
      },
      {
        "token": "--wje-color-info-5",
        "value": "hsla(208, 6%, 55%, 1)"
      },
      {
        "token": "--wje-color-info-6",
        "value": "hsla(203, 6%, 62%, 1)"
      },
      {
        "token": "--wje-color-info-7",
        "value": "hsla(213, 6%, 69%, 1)"
      },
      {
        "token": "--wje-color-info-8",
        "value": "hsla(203, 5%, 71%, 1)"
      },
      {
        "token": "--wje-color-info-9",
        "value": "hsla(210, 7%, 78%, 1)"
      },
      {
        "token": "--wje-color-info-10",
        "value": "hsla(204, 6%, 85%, 1)"
      },
      {
        "token": "--wje-color-info-11",
        "value": "hsla(210, 5%, 92%, 1)"
      }
    ]
  },
  "--wje-color-contrast": {
    "light": [
      {
        "token": "--wje-color-contrast-0",
        "value": "hsla(0, 0%, 100%, 1)"
      },
      {
        "token": "--wje-color-contrast-1",
        "value": "hsla(0, 0%, 98%, 1)"
      },
      {
        "token": "--wje-color-contrast-2",
        "value": "hsla(240, 5%, 96%, 1)"
      },
      {
        "token": "--wje-color-contrast-3",
        "value": "hsla(240, 6%, 90%, 1)"
      },
      {
        "token": "--wje-color-contrast-4",
        "value": "hsla(240, 5%, 84%, 1)"
      },
      {
        "token": "--wje-color-contrast-5",
        "value": "hsla(240, 5%, 65%, 1)"
      },
      {
        "token": "--wje-color-contrast-6",
        "value": "hsla(240, 4%, 46%, 1)"
      },
      {
        "token": "--wje-color-contrast-7",
        "value": "hsla(240, 5%, 34%, 1)"
      },
      {
        "token": "--wje-color-contrast-8",
        "value": "hsla(240, 5%, 26%, 1)"
      },
      {
        "token": "--wje-color-contrast-9",
        "value": "hsla(240, 4%, 16%, 1)"
      },
      {
        "token": "--wje-color-contrast-10",
        "value": "hsla(240, 6%, 10%, 1)"
      },
      {
        "token": "--wje-color-contrast-11",
        "value": "hsla(240, 7%, 8%, 1)"
      }
    ],
    "dark": [
      {
        "token": "--wje-color-contrast-0",
        "value": "hsla(240, 3%, 13%, 1)"
      },
      {
        "token": "--wje-color-contrast-1",
        "value": "hsla(240, 6%, 10%, 1)"
      },
      {
        "token": "--wje-color-contrast-2",
        "value": "hsla(0, 0%, 0%, 1)"
      },
      {
        "token": "--wje-color-contrast-3",
        "value": "hsla(240, 5%, 30%, 1)"
      },
      {
        "token": "--wje-color-contrast-4",
        "value": "hsla(240, 5%, 41%, 1)"
      },
      {
        "token": "--wje-color-contrast-5",
        "value": "hsla(240, 4%, 58%, 1)"
      },
      {
        "token": "--wje-color-contrast-6",
        "value": "hsla(240, 5%, 75%, 1)"
      },
      {
        "token": "--wje-color-contrast-7",
        "value": "hsla(240, 5%, 84%, 1)"
      },
      {
        "token": "--wje-color-contrast-8",
        "value": "hsla(240, 6%, 90%, 1)"
      },
      {
        "token": "--wje-color-contrast-9",
        "value": "hsla(240, 5%, 96%, 1)"
      },
      {
        "token": "--wje-color-contrast-10",
        "value": "hsla(0, 0%, 98%, 1)"
      },
      {
        "token": "--wje-color-contrast-11",
        "value": "hsla(0, 0%, 100%, 1)"
      }
    ]
  }
} as const;
