project_id: '663282'
api_token: '1c774b040df95ab027d58270041d634b77bc0cd067400ec8006e7be9f8c25efdfc563421143bdb1f'
preserve_hierarchy: true

files:
  - source: /i18n/sk/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    ignore:
      - /docs/cli/commands/**/*
      - /docs/native/**/*
